#!/usr/bin/env python3
"""Fail-closed verification for the WP-00 G3 reconciled baseline."""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


g3 = load_module("generate_g3", HERE / "generate_g3.py")
gf = load_module("governed_fingerprint", HERE / "governed_fingerprint.py")


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fail(message: str) -> None:
    raise AssertionError(message)


def static_verify() -> None:
    files, a4 = g3.expected_files()
    failures = g3.check_files(files)
    if failures:
        fail("generated bytes drifted:\n  " + "\n  ".join(failures))
    for relative, expected in files.items():
        try:
            committed = g3.git_blob("HEAD", g3.canonical_repo_path(relative))
        except RuntimeError as exc:
            fail(f"generated artifact is not committed at HEAD: {relative}: {exc}")
        if committed != expected:
            fail(f"committed artifact differs from deterministic bytes: {relative}")
    print(f"G3-COMMITTED-BLOBS PASS: {len(files)} generated artifacts match HEAD Git blobs")
    print(
        "G3-INPUT-BIND PASS: signed G2 blob/receipt/checksum unchanged "
        f"({g3.G2_MANIFEST_SHA256}, {g3.G2_MANIFEST_SIZE} bytes)"
    )

    legacy_sources = g3.legacy_paths()
    if len(legacy_sources) != 40:
        fail("legacy source count is not 40")
    inventory_lines = [
        line for line in (ROOT / g3.LEGACY_SUMS).read_text().splitlines()
        if line and not line.startswith("#")
    ]
    if len(inventory_lines) != 40:
        fail("legacy checksum inventory must contain 40 entries")
    for source, inventory in zip(legacy_sources, inventory_lines, strict=True):
        frozen = g3.git_blob(g3.FROZEN_G2_COMMIT, source)
        current = (ROOT / source).read_bytes()
        archived = (ROOT / g3.LEGACY_DIR / Path(source).name).read_bytes()
        if current != frozen or archived != frozen:
            fail(f"legacy migration bytes drifted: {source}")
        expected_line = f"{digest(frozen)}  001-040/{Path(source).name}"
        if inventory != expected_line:
            fail(f"legacy checksum inventory mismatch: {source}")
    print("LEGACY-ARCHIVE PASS: exactly 40 byte-identical provenance files; ordered checksums match")

    baseline = (ROOT / g3.BASELINE_SQL).read_text()
    manifest = json.loads((ROOT / g3.G2_MANIFEST_PATH).read_bytes())
    if len(re.findall(r"^CREATE TABLE public\.", baseline, re.M)) != 64:
        fail("baseline must create exactly 64 public product tables")
    if len(re.findall(r"^CREATE OR REPLACE FUNCTION public\.", baseline, re.M)) != 10:
        fail("baseline must create exactly 10 application functions")
    if len(re.findall(r"^CREATE SEQUENCE public\.", baseline, re.M)) != 1:
        fail("baseline must create exactly one product sequence")
    for table in manifest["tables"]:
        if f"CREATE TABLE {table} (" not in baseline:
            fail(f"baseline missing table {table}")
    for grant in manifest["target_grants"]["application_functions"]:
        if grant["public_revoke_sql"] + ";" not in baseline:
            fail(f"baseline missing signature-scoped PUBLIC revoke: {grant['identity_signature']}")
    if "REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public" in baseline:
        fail("baseline must not revoke PUBLIC from extension functions")
    if re.search(r"migrations/(?:legacy|0[0-4][0-9]_)", baseline):
        fail("baseline selects or references legacy migrations")
    first_extension = baseline.index("CREATE EXTENSION")
    role_switch = baseline.index("SET LOCAL ROLE clarityit_owner")
    if first_extension > role_switch:
        fail("extensions must be installed before the owner-role switch")
    if "SET LOCAL search_path = pg_catalog, public;" not in baseline:
        fail("baseline must resolve PostgreSQL built-ins before public extension wrappers")
    print("BASELINE-GEN PASS: two independent generations are byte-identical; nested G2 shape emitted completely")

    roles = (ROOT / g3.ROLES_SQL).read_text()
    for name in ("clarityit", "clarityit_app", "clarityit_owner", "clarityit_migrator", "clarityit_admin"):
        if f"CREATE ROLE {name} " not in roles:
            fail(f"role bootstrap missing {name}")
    for membership in manifest["target_memberships"]:
        if membership["sql"] + ";" not in roles:
            fail(f"role bootstrap membership drift: {membership['member']}")
    if "REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC" not in roles:
        fail("owner-scoped default PUBLIC function revoke missing")
    role_statements = [line for line in roles.splitlines() if line.startswith("CREATE ROLE ")]
    if any("PASSWORD" in line.upper() for line in role_statements) or any(
        re.search(r"(?<!NO)SUPERUSER", line) for line in role_statements
    ):
        fail("role bootstrap contains a credential or superuser target posture")
    print("PRIVILEGE PASS: five roles, exact memberships, owner boundary, grants, and default privileges are bound")

    control = json.loads((ROOT / g3.CONTROL_MANIFEST).read_bytes())
    platform = (ROOT / g3.PLATFORM_SQL).read_bytes()
    if set(control["tables"]) != set(g3.CONTROL_TABLES) or len(control["tables"]) != 4:
        fail("control manifest must describe exactly four platform tables")
    if control["platform_sql_sha256"] != digest(platform):
        fail("control manifest is not bound to 0000_platform.sql")
    print("CONTROL PASS: four platform tables, constraints, immutability controls, ownership, and ACL scope are bound")

    seed = (ROOT / g3.SEED_SQL).read_text()
    canonical_names = {row[0] for row in g3.CANONICAL_PERMISSIONS}
    for name in canonical_names:
        if seed.count(f"'{name}'") < 1:
            fail(f"seed missing canonical permission {name}")
    legacy_names = {name.replace(".update", ".edit") for name in canonical_names}
    if any(f"'{name}'" in seed for name in legacy_names):
        fail("seed contains a legacy .edit permission row")
    baseline_sha = digest((ROOT / g3.BASELINE_SQL).read_bytes())
    if baseline_sha not in seed:
        fail("seed revision row is not bound to baseline SQL")
    print("SEED-EQUIV PASS: deterministic seven-name permission seed and baseline revision binding match")

    detached = [
        line for line in (ROOT / g3.V2_SUMS).read_text().splitlines()
        if line and not line.startswith("#")
    ]
    for line in detached:
        expected_sha, relative = line.split("  ", 1)
        if digest((ROOT / relative).read_bytes()) != expected_sha:
            fail(f"detached checksum mismatch: {relative}")

    components = [
        ("product_manifest_blob_sha256", g3.G2_MANIFEST_SHA256.encode("ascii")),
        ("control_manifest", (ROOT / g3.CONTROL_MANIFEST).read_bytes()),
        ("baseline_sql", (ROOT / g3.BASELINE_SQL).read_bytes()),
        ("seed_sql", (ROOT / g3.SEED_SQL).read_bytes()),
        ("role_bootstrap_sql", (ROOT / g3.ROLES_SQL).read_bytes()),
        ("legacy_checksum_inventory", (ROOT / g3.LEGACY_SUMS).read_bytes()),
    ]
    installation_sha = g3.composite_digest(components)
    if installation_sha != a4["composite"]["sha256"]:
        fail("composite installation identity mismatch")
    if json.loads((ROOT / g3.A4_MANIFEST).read_bytes()) != a4:
        fail("A4 manifest bytes do not describe the recomputed artifact")
    for index, (label, data) in enumerate(components):
        tampered = list(components)
        tampered[index] = (label, data + b"\x00")
        if g3.composite_digest(tampered) == installation_sha:
            fail(f"composite identity did not reject tampered {label}")
    print("NEGATIVE PASS: a one-byte change to every composite component changes installation identity")
    print(f"A4-BIND PASS: composite installation sha256 {installation_sha}")

    receipt_path = ROOT / "docs/migration/wp00/g3/G3-APPROVALS.md"
    receipt_bytes = receipt_path.read_bytes()
    if g3.git_blob("HEAD", g3.canonical_repo_path(receipt_path.relative_to(ROOT))) != receipt_bytes:
        fail("G3 approval receipt differs from the committed HEAD blob")
    receipt = receipt_bytes.decode()
    block_match = re.search(r"```g3-receipt-identity\n(.*?)\n```", receipt, re.S)
    if not block_match:
        fail("G3 approval receipt has no machine-readable identity block")
    receipt_fields = {}
    for line in block_match.group(1).splitlines():
        key, separator, value = line.partition(":")
        if not separator:
            fail(f"malformed G3 receipt identity line: {line}")
        receipt_fields[key.strip()] = value.strip()
    expected_receipt = {
        "product_manifest_blob_sha256": g3.G2_MANIFEST_SHA256,
        "product_manifest_blob_size": str(g3.G2_MANIFEST_SIZE),
        "control_manifest_sha256": digest((ROOT / g3.CONTROL_MANIFEST).read_bytes()),
        "composite_installation_sha256": installation_sha,
        "database_name": g3.POSTGRES_DB,
        "postgres_major": "16",
    }
    if receipt_fields != expected_receipt:
        fail(f"G3 receipt identity differs from generated artifacts: {receipt_fields}")
    print("G3-RECEIPT-BIND PASS: committed receipt product/control/composite identities match committed artifact bytes")


def open_readonly(dsn: str):
    try:
        import psycopg2  # type: ignore
    except ImportError as exc:
        raise RuntimeError("live verification requires psycopg2-binary") from exc
    connection = psycopg2.connect(dsn, connect_timeout=10)
    connection.autocommit = False
    cursor = connection.cursor()
    cursor.execute("SET TRANSACTION READ ONLY")
    return connection, cursor


def normalize_list(value: list[dict]) -> list[str]:
    return sorted(json.dumps(item, sort_keys=True, separators=(",", ":")) for item in value)


def signed_relation_projection(relations: list[dict]) -> list[dict]:
    """Project live profiler rows onto the deliberate G2 relation contract.

    capture_schema.py reports a derived composite-type display name for every
    relation.  The signed G2 target intentionally excludes that non-DDL field
    and binds schema, name, kind, and persistence only.
    """
    fields = ("schema", "name", "kind", "persistence")
    return [{field: row[field] for field in fields} for row in relations]


def verify_product_shape(capture: dict, signed: dict) -> None:
    public_relations = [row for row in capture["relations"] if row["schema"] == "public"]
    expected_relation_fields = {"schema", "name", "kind", "persistence"}
    if any(set(row) != expected_relation_fields for row in signed["relations"]):
        fail("signed G2 relation shape changed")
    if normalize_list(signed_relation_projection(public_relations)) != normalize_list(signed["relations"]):
        fail("live public relations differ from signed G2 manifest")
    if normalize_list([s for s in capture["sequences"] if s["schema"] == "public"]) != normalize_list(signed["sequences"]):
        fail("live public sequences differ from signed G2 manifest")
    for table_name, target in signed["tables"].items():
        for section in ("columns", "constraints", "indexes", "triggers"):
            live = capture[section].get(table_name, [])
            if normalize_list(live) != normalize_list(target[section]):
                fail(f"live {section} differ for {table_name}")
    app_signatures = {
        (row["schema"], row["name"], row["args"])
        for row in signed["target_grants"]["application_functions"]
    }
    live_functions = [
        row for row in capture["functions"]
        if (row["schema"], row["name"], row["args"]) in app_signatures
    ]
    target_functions = [
        row for row in signed["functions"]
        if (row["schema"], row["name"], row["args"]) in app_signatures
    ]
    if normalize_list(live_functions) != normalize_list(target_functions):
        fail("live application functions differ from signed G2 manifest")
    if len([key for key in capture["columns"] if key.startswith("public.")]) != 64:
        fail("live public product table count is not 64")


def verify_roles_and_privileges(cur, signed: dict) -> None:
    role_names = [row["name"] for row in signed["target_roles"]]
    cur.execute(
        "SELECT rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolreplication, rolbypassrls "
        "FROM pg_roles WHERE rolname = ANY(%s) ORDER BY rolname",
        (role_names,),
    )
    live_roles = {
        row[0]: {
            "superuser": row[1], "inherit": row[2], "createrole": row[3],
            "createdb": row[4], "canlogin": row[5], "replication": row[6], "bypassrls": row[7],
        }
        for row in cur.fetchall()
    }
    expected_roles = {row["name"]: row["flags"] for row in signed["target_roles"]}
    if live_roles != expected_roles:
        fail("live target role flags differ from signed G2 posture")

    cur.execute(
        "SELECT member.rolname, granted.rolname, am.admin_option, am.inherit_option, am.set_option "
        "FROM pg_auth_members am JOIN pg_roles member ON member.oid=am.member "
        "JOIN pg_roles granted ON granted.oid=am.roleid "
        "WHERE member.rolname = ANY(%s) AND granted.rolname = ANY(%s) ORDER BY 1,2",
        (role_names, role_names),
    )
    memberships = [
        {"member": r[0], "role_of": r[1], "admin_option": r[2], "inherit_option": r[3], "set_option": r[4]}
        for r in cur.fetchall()
    ]
    expected_memberships = [
        {key: row[key] for key in ("member", "role_of", "admin_option", "inherit_option", "set_option")}
        for row in signed["target_memberships"]
    ]
    if normalize_list(memberships) != normalize_list(expected_memberships):
        fail("live membership options differ from signed G2 posture")

    cur.execute(
        "SELECT c.relname, a.privilege_type, a.is_grantable FROM pg_class c "
        "JOIN pg_namespace n ON n.oid=c.relnamespace, "
        "aclexplode(c.relacl) a WHERE n.nspname='public' AND c.relkind='r' "
        "AND pg_get_userbyid(a.grantee)='clarityit_app' ORDER BY 1,2"
    )
    table_acl = {(r[0], r[1], r[2]) for r in cur.fetchall()}
    expected_table_acl = {
        (row["name"], privilege, row["grant_option"])
        for row in signed["target_grants"]["tables"] for privilege in row["privileges"]
    }
    if table_acl != expected_table_acl:
        fail("live table grants differ from signed G2 inventory")

    cur.execute(
        "SELECT c.relname, a.privilege_type, a.is_grantable FROM pg_class c "
        "JOIN pg_namespace n ON n.oid=c.relnamespace, "
        "aclexplode(c.relacl) a WHERE n.nspname='public' AND c.relkind='S' "
        "AND pg_get_userbyid(a.grantee)='clarityit_app' ORDER BY 1,2"
    )
    sequence_acl = {(r[0], r[1], r[2]) for r in cur.fetchall()}
    expected_sequence_acl = {
        (row["name"], privilege, row["grant_option"])
        for row in signed["target_grants"]["sequences"] for privilege in row["privileges"]
    }
    if sequence_acl != expected_sequence_acl:
        fail("live sequence grants differ from signed G2 inventory")

    cur.execute(
        "SELECT a.privilege_type, a.is_grantable FROM pg_namespace n, aclexplode(n.nspacl) a "
        "WHERE n.nspname='public' AND pg_get_userbyid(a.grantee)='clarityit_app' ORDER BY 1"
    )
    if cur.fetchall() != [("USAGE", False)]:
        fail("live public-schema grant differs from signed G2 inventory")

    signatures = [row["identity_signature"] for row in signed["target_grants"]["application_functions"]]
    cur.execute(
        "SELECT n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')', "
        "a.grantee = 0, pg_get_userbyid(a.grantee), a.privilege_type, a.is_grantable "
        "FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace, "
        "aclexplode(coalesce(p.proacl, acldefault('f',p.proowner))) a "
        "WHERE n.nspname='public' AND (n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')') = ANY(%s) "
        "ORDER BY 1,2,3",
        (signatures,),
    )
    app_acl_rows = cur.fetchall()
    app_exec = {(r[0], r[3], r[4]) for r in app_acl_rows if r[2] == "clarityit_app"}
    if app_exec != {(signature, "EXECUTE", False) for signature in signatures}:
        fail("live application-function grants differ from signed G2 inventory")
    if any(r[1] and r[3] == "EXECUTE" for r in app_acl_rows):
        fail("PUBLIC EXECUTE remains on an application function")

    cur.execute(
        "SELECT n.nspname, c.relname, r.rolname FROM pg_class c "
        "JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_roles r ON r.oid=c.relowner "
        "WHERE n.nspname='public' AND c.relkind IN ('r','S','i') AND r.rolname <> 'clarityit_owner'"
    )
    if cur.fetchall():
        fail("a public product relation/index/sequence is not owned by clarityit_owner")
    cur.execute(
        "SELECT r.rolname FROM pg_namespace n JOIN pg_roles r ON r.oid=n.nspowner WHERE n.nspname='public'"
    )
    if cur.fetchone()[0] != "clarityit_owner":
        fail("public schema is not owned by clarityit_owner")
    cur.execute(
        "SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace "
        "JOIN pg_roles r ON r.oid=p.proowner WHERE n.nspname='public' "
        "AND ('public.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')') = ANY(%s) "
        "AND r.rolname <> 'clarityit_owner'",
        (signatures,),
    )
    if cur.fetchall():
        fail("an application function is not owned by clarityit_owner")

    cur.execute(
        "SELECT d.defaclobjtype, a.grantee=0, pg_get_userbyid(a.grantee), "
        "a.privilege_type, a.is_grantable FROM pg_default_acl d "
        "LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace, aclexplode(d.defaclacl) a "
        "WHERE pg_get_userbyid(d.defaclrole)='clarityit_owner' AND n.nspname='public' "
        "ORDER BY 1,2,3,4"
    )
    default_rows = cur.fetchall()
    app_defaults = {(r[0], r[3], r[4]) for r in default_rows if r[2] == "clarityit_app"}
    object_codes = {"TABLES": "r", "SEQUENCES": "S", "FUNCTIONS": "f"}
    expected_defaults = {
        (object_codes[row["object_type"]], privilege, False)
        for row in signed["target_default_privileges"] for privilege in row["privileges"]
    }
    if app_defaults != expected_defaults:
        fail("live default privileges differ from signed G2 inventory")
    if any(r[0] == "f" and r[1] and r[3] == "EXECUTE" for r in default_rows):
        fail("owner default privileges still grant PUBLIC EXECUTE on future functions")


def verify_control(cur, control: dict) -> None:
    cur.execute(
        "SELECT table_name FROM information_schema.tables WHERE table_schema='platform' AND table_type='BASE TABLE' ORDER BY 1"
    )
    if [row[0] for row in cur.fetchall()] != sorted(control["tables"]):
        fail("live platform table set differs from control manifest")
    for table_name, spec in control["tables"].items():
        cur.execute(
            "SELECT column_name, data_type, is_nullable, column_default FROM information_schema.columns "
            "WHERE table_schema='platform' AND table_name=%s ORDER BY ordinal_position",
            (table_name,),
        )
        live_rows = cur.fetchall()
        live = [(r[0], r[1], r[2] == "YES") for r in live_rows]
        expected = [
            (column["name"], column["type"], "NOT NULL" not in column["sql_suffix"])
            for column in spec["columns"]
        ]
        if live != expected:
            fail(f"live platform columns differ: {table_name}")
        for live_row, column in zip(live_rows, spec["columns"], strict=True):
            default_marker = " DEFAULT "
            expected_default = (
                column["sql_suffix"].split(default_marker, 1)[1]
                if default_marker in column["sql_suffix"] else None
            )
            if live_row[3] != expected_default:
                fail(f"live platform column default differs: {table_name}.{column['name']}")
        expected_constraints = {
            re.match(r"CONSTRAINT\s+(\S+)", value).group(1) for value in spec["constraints"]
        }
        cur.execute(
            "SELECT con.conname FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid "
            "JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='platform' AND c.relname=%s ORDER BY 1",
            (table_name,),
        )
        if {row[0] for row in cur.fetchall()} != expected_constraints:
            fail(f"live platform constraints differ: {table_name}")
        expected_indexes = {
            re.match(r"CREATE (?:UNIQUE )?INDEX\s+(\S+)", value).group(1)
            for value in spec["indexes"]
        }
        cur.execute(
            "SELECT indexname FROM pg_indexes WHERE schemaname='platform' AND tablename=%s "
            "AND indexname <> ALL(%s) ORDER BY 1",
            (table_name, list(expected_constraints)),
        )
        if {row[0] for row in cur.fetchall()} != expected_indexes:
            fail(f"live platform non-constraint indexes differ: {table_name}")
    cur.execute(
        "SELECT p.proname||'('||pg_get_function_identity_arguments(p.oid)||')' FROM pg_proc p "
        "JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='platform' ORDER BY 1"
    )
    live_functions = {f"platform.{row[0]}" for row in cur.fetchall()}
    if live_functions != set(control["functions"]):
        fail("live platform functions differ from control manifest")
    cur.execute(
        "SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace "
        "JOIN pg_roles r ON r.oid=p.proowner WHERE n.nspname='platform' AND r.rolname <> 'clarityit_owner'"
    )
    if cur.fetchall():
        fail("a platform function is not owned by clarityit_owner")
    cur.execute(
        "SELECT n.nspname||'.'||c.relname||'.'||t.tgname FROM pg_trigger t "
        "JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace "
        "WHERE n.nspname='platform' AND NOT t.tgisinternal ORDER BY 1"
    )
    if {row[0] for row in cur.fetchall()} != set(control["triggers"]):
        fail("live platform triggers differ from control manifest")
    cur.execute(
        "SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace "
        "JOIN pg_roles r ON r.oid=c.relowner WHERE n.nspname='platform' AND c.relkind='r' "
        "AND r.rolname <> 'clarityit_owner'"
    )
    if cur.fetchall():
        fail("a platform table is not owned by clarityit_owner")
    cur.execute(
        "SELECT r.rolname FROM pg_namespace n JOIN pg_roles r ON r.oid=n.nspowner WHERE n.nspname='platform'"
    )
    if cur.fetchone()[0] != "clarityit_owner":
        fail("platform schema is not owned by clarityit_owner")
    cur.execute(
        "SELECT table_name FROM information_schema.role_table_grants "
        "WHERE table_schema='platform' AND grantee='clarityit_app'"
    )
    if cur.fetchall():
        fail("clarityit_app has an unauthorized platform table grant")
    cur.execute(
        "SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace, "
        "aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a "
        "WHERE n.nspname='platform' AND (a.grantee=0 OR pg_get_userbyid(a.grantee)='clarityit_app')"
    )
    if cur.fetchall():
        fail("PUBLIC or clarityit_app has an unauthorized platform-function grant")


def seed_rows(cur) -> dict:
    cur.execute(
        "SELECT id::text,name,description,resource,action,risk_level,created_at::text "
        "FROM public.permissions ORDER BY name"
    )
    permissions = cur.fetchall()
    cur.execute(
        "SELECT version,name,checksum,source_commit,applied_at::text,applied_by,execution_ms,success "
        "FROM platform.schema_revisions ORDER BY version"
    )
    revisions = cur.fetchall()
    return {"permissions": permissions, "revisions": revisions}


def live_verify(dsn_a: str, dsn_b: str) -> None:
    cs = load_module("capture_schema_g3", ROOT / "scripts/profile/capture_schema.py")
    signed = json.loads((ROOT / g3.G2_MANIFEST_PATH).read_bytes())
    control = json.loads((ROOT / g3.CONTROL_MANIFEST).read_bytes())
    connections = []
    captures = []
    seeds = []
    try:
        for index, dsn in enumerate((dsn_a, dsn_b), start=1):
            connection, cursor = open_readonly(dsn)
            connections.append(connection)
            cursor.execute("SELECT current_database()")
            if cursor.fetchone()[0] != g3.POSTGRES_DB:
                fail(f"fresh install {index} database name is not {g3.POSTGRES_DB}")
            capture = cs.build_manifest(cursor, f"g3-fresh-{index}")
            verify_product_shape(capture, signed)
            verify_roles_and_privileges(cursor, signed)
            verify_control(cursor, control)
            captures.append(capture)
            seeds.append(seed_rows(cursor))
        fingerprints = [cs.fingerprint_of(capture) for capture in captures]
        if fingerprints[0] != fingerprints[1]:
            fail(f"fresh profiler fingerprints differ: {fingerprints}")
        if seeds[0] != seeds[1]:
            fail("fresh seed/revision rows differ")
        if len(seeds[0]["permissions"]) != 7 or len(seeds[0]["revisions"]) != 1:
            fail("fresh seed contract contains unexpected rows")
        if {row[1] for row in seeds[0]["permissions"]} != {row[0] for row in g3.CANONICAL_PERMISSIONS}:
            fail("fresh permission rows differ from the canonical seven-name contract")
        revision = seeds[0]["revisions"][0]
        if revision[0] != g3.BASELINE_VERSION or revision[2] != digest((ROOT / g3.BASELINE_SQL).read_bytes()):
            fail("fresh revision row differs from the baseline version/checksum contract")
        print(f"FRESH-EQUIV PASS: two independent installs share profiler fingerprint {fingerprints[0]}")
        print("PRODUCT-CONFORM PASS: each install conforms to signed G2 across 64 tables, 10 app functions, PKs, indexes, triggers, grants, ownership, and memberships")
        print("CONTROL-LIVE PASS: each install conforms to the separate four-table control manifest")
        print("SEED-LIVE PASS: deterministic permission and revision rows match")
    finally:
        for connection in connections:
            connection.rollback()
            connection.close()


def governed_fingerprint_of(dsn: str) -> str:
    """Compute the governed target fingerprint from a live read-only DSN."""
    signed = json.loads((ROOT / g3.G2_MANIFEST_PATH).read_bytes())
    control = json.loads((ROOT / g3.CONTROL_MANIFEST).read_bytes())
    connection, cursor = open_readonly(dsn)
    try:
        capture = gf.governed_capture(cursor, signed, control)
        target_names = {r["name"] for r in signed["target_roles"]}
        gf.assert_extension_owner_invariant(capture, target_names)
        return gf.governed_fingerprint(capture)
    finally:
        connection.rollback()
        connection.close()


def pre_adopt_verify(dsn: str) -> None:
    """Read-only pre-adoption checks against a P3 source database.

    Verifies the ADOPTION-CONTRACT preconditions BEFORE any write: the
    source matches the approved P3 golden fingerprint, PG16 + clarityit,
    required extensions present, the 64-table product shape conforms to
    the signed G2 manifest, clarityit exists as the bootstrap superuser
    owning the extensions, and the target/legacy identities are absent.
    Emits ADOPT-P3 PRECONDITIONS PASS.  Performs zero writes.
    """
    cs = load_module("capture_schema_pre", ROOT / "scripts/profile/capture_schema.py")
    signed = json.loads((ROOT / g3.G2_MANIFEST_PATH).read_bytes())
    connection, cursor = open_readonly(dsn)
    try:
        cursor.execute("SELECT current_database()")
        if cursor.fetchone()[0] != g3.POSTGRES_DB:
            fail(f"pre-adoption database name is not {g3.POSTGRES_DB}")
        cursor.execute("SHOW server_version_num")
        pg_major = int(str(cursor.fetchone()[0])[:2])
        if pg_major != 16:
            fail(f"pre-adoption PostgreSQL major is not 16 (got {pg_major})")

        capture = cs.build_manifest(cursor, "p3-pre-adopt")
        live_fp = cs.fingerprint_of(capture)
        if live_fp != gf.P3_GOLDEN_FINGERPRINT:
            fail(
                f"pre-adoption source fingerprint {live_fp} does not match the "
                f"G1-approved P3 golden {gf.P3_GOLDEN_FINGERPRINT}"
            )
        print(f"ADOPT-P3 SOURCE-FINGERPRINT PASS: {live_fp}")

        verify_product_shape(capture, signed)

        cursor.execute(
            "SELECT count(*) FROM pg_extension WHERE extname IN ('pgcrypto','citext','pg_trgm')"
        )
        if cursor.fetchone()[0] != 3:
            fail("pre-adoption source is missing a required extension")

        cursor.execute(
            "SELECT count(*) FROM pg_roles WHERE rolname = 'clarityit' AND rolsuper"
        )
        if cursor.fetchone()[0] != 1:
            fail("pre-adoption requires the P3 bootstrap superuser clarityit")
        cursor.execute(
            "SELECT count(DISTINCT e.extname) FROM pg_extension e "
            "JOIN pg_roles r ON r.oid = e.extowner "
            "WHERE e.extname IN ('pgcrypto','citext','pg_trgm') AND r.rolname = 'clarityit'"
        )
        if cursor.fetchone()[0] != 3:
            fail("pre-adoption requires clarityit to own pgcrypto, citext, and pg_trgm")

        cursor.execute(
            "SELECT count(*) FROM pg_roles WHERE rolname IN ("
            "'clarityit_app','clarityit_owner','clarityit_migrator','clarityit_admin',"
            "'legacy_ext_owner','g3_adopt_admin')"
        )
        if cursor.fetchone()[0] != 0:
            fail("pre-adoption requires target/legacy identities to be absent (single-shot)")
        cursor.execute("SELECT count(*) FROM pg_namespace WHERE nspname = 'platform'")
        if cursor.fetchone()[0] != 0:
            fail("pre-adoption requires no existing platform schema")
    finally:
        connection.rollback()
        connection.close()
    print("ADOPT-P3 PRECONDITIONS PASS: source is the approved P3 shape; no writes performed")


def post_adopt_verify(dsn_fresh: str, dsn_adopted: str) -> None:
    """Post-adoption conformance + governed convergence check.

    Verifies the adopted database: product-shape and roles/privileges
    conformance, control conformance, the extension-owner invariant, and
    exact equality of the governed fingerprint between the fresh install
    and the adopted P3 source.  Emits ADOPT-P3 CONVERGE PASS.
    """
    cs = load_module("capture_schema_adopt", ROOT / "scripts/profile/capture_schema.py")
    signed = json.loads((ROOT / g3.G2_MANIFEST_PATH).read_bytes())
    control = json.loads((ROOT / g3.CONTROL_MANIFEST).read_bytes())

    connection, cursor = open_readonly(dsn_adopted)
    try:
        cursor.execute("SELECT current_database()")
        if cursor.fetchone()[0] != g3.POSTGRES_DB:
            fail(f"post-adoption database name is not {g3.POSTGRES_DB}")
        capture = cs.build_manifest(cursor, "p3-post-adopt")
        verify_product_shape(capture, signed)
        verify_roles_and_privileges(cursor, signed)
        verify_control(cursor, control)
        cursor.execute(
            "SELECT pg_get_userbyid(datdba) FROM pg_database WHERE datname = current_database()"
        )
        if cursor.fetchone()[0] != "clarityit_owner":
            fail("post-adoption database is not owned by clarityit_owner")

        # Validate the adoption source_profiles row.
        cursor.execute(
            "SELECT profile_id, schema_fingerprint, postgres_major, source_commit, approved_by "
            "FROM platform.source_profiles WHERE profile_id = %s",
            (g3.P3_PROFILE_ID,),
        )
        row = cursor.fetchone()
        if row is None:
            fail("post-adoption platform.source_profiles is missing the P3 adoption row")
        sp_profile_id, sp_fp, sp_major, sp_commit, sp_approved = row
        if sp_fp != g3.P3_GOLDEN_FINGERPRINT:
            fail(f"post-adoption source_profiles fingerprint mismatch: {sp_fp}")
        if sp_major != 16:
            fail(f"post-adoption source_profiles postgres_major mismatch: {sp_major}")
        if sp_commit != g3.P3_SOURCE_COMMIT:
            fail(f"post-adoption source_profiles source_commit mismatch: {sp_commit}")
        if sp_approved != g3.G1_APPROVAL_REF:
            fail(f"post-adoption source_profiles approved_by mismatch: {sp_approved}")

        # Validate the adoption schema_revisions row.
        baseline_sha = hashlib.sha256(
            (ROOT / g3.BASELINE_SQL).read_bytes()
        ).hexdigest()
        cursor.execute(
            "SELECT version, name, checksum, success FROM platform.schema_revisions "
            "WHERE version = %s AND name = 'adopt-p3'",
            (g3.BASELINE_VERSION,),
        )
        row = cursor.fetchone()
        if row is None:
            fail("post-adoption platform.schema_revisions is missing the adopt-p3 row")
        rev_version, rev_name, rev_checksum, rev_success = row
        if rev_checksum != baseline_sha:
            fail(f"post-adoption schema_revisions checksum mismatch: {rev_checksum} != {baseline_sha}")
        if not rev_success:
            fail("post-adoption schema_revisions adopt-p3 row is not successful")

        # Validate the canonical permission rows.
        canonical_names = {row[0] for row in g3.CANONICAL_PERMISSIONS}
        cursor.execute(
            "SELECT name FROM public.permissions ORDER BY name"
        )
        live_names = {r[0] for r in cursor.fetchall()}
        if live_names != canonical_names:
            fail(f"post-adoption permission rows differ from canonical seven: {live_names}")
        if any(n.endswith(".edit") for n in live_names):
            fail("post-adoption permissions contain a legacy .edit row")
    finally:
        connection.rollback()
        connection.close()

    fresh_fp = governed_fingerprint_of(dsn_fresh)
    adopted_fp = governed_fingerprint_of(dsn_adopted)
    if fresh_fp != adopted_fp:
        fail(
            f"ADOPT-P3 CONVERGE FAIL: fresh governed {fresh_fp} != adopted {adopted_fp}"
        )
    print(f"ADOPT-P3 CONVERGE PASS: fresh and adopted share governed fingerprint {fresh_fp}")


def receipt_bind_verify() -> None:
    """Verify the receipt-to-producing-commit binding (commit 2 only).

    Confirms that the producing commit recorded in the receipt:
      1. exists as a git object;
      2. is an ancestor of the current HEAD (the receipt tip); and
      3. the ONLY file changed between the producing commit and HEAD is
         ``docs/migration/wp00/g3/G3-APPROVALS.md`` (the receipt-only
         boundary).
    This makes the two-commit structure machine-verifiable.
    """
    import subprocess
    receipt_path = ROOT / "docs/migration/wp00/g3/G3-APPROVALS.md"
    receipt_text = receipt_path.read_text()
    match = re.search(r"[Pp]roducing commit: `([0-9a-f]{40})`", receipt_text)
    if not match:
        fail("receipt has no 'producing commit: <40-hex>' line")
    producing_sha = match.group(1)

    # 1. producing commit exists
    proc = subprocess.run(
        ["git", "cat-file", "-t", producing_sha],
        cwd=ROOT, capture_output=True,
    )
    if proc.returncode != 0 or proc.stdout.strip() != b"commit":
        fail(f"producing commit {producing_sha} does not exist as a git commit")

    # 2. producing commit is an ancestor of HEAD (the receipt tip)
    proc = subprocess.run(
        ["git", "merge-base", "--is-ancestor", producing_sha, "HEAD"],
        cwd=ROOT,
    )
    if proc.returncode != 0:
        fail(f"producing commit {producing_sha} is not an ancestor of HEAD (receipt tip)")

    # 3. only G3-APPROVALS.md changed between producing and HEAD
    proc = subprocess.run(
        ["git", "diff", "--name-only", producing_sha, "HEAD"],
        cwd=ROOT, capture_output=True,
    )
    if proc.returncode != 0:
        fail(f"cannot diff {producing_sha}..HEAD")
    changed = [line for line in proc.stdout.decode().splitlines() if line.strip()]
    receipt_relative = g3.canonical_repo_path(receipt_path.relative_to(ROOT))
    non_receipt = [f for f in changed if f != receipt_relative]
    if non_receipt:
        fail(
            f"producing-tip-to-receipt-tip changed files other than the receipt: "
            f"{non_receipt}"
        )
    print(f"G3-RECEIPT-BIND-PROVENANCE PASS: producing commit {producing_sha} exists, "
          f"is an ancestor of HEAD, and the only producing→receipt change is {receipt_relative}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("static", help="verify committed/generated artifact bytes")
    live = sub.add_parser("live", help="compare two independently installed PostgreSQL 16 databases")
    live.add_argument("--dsn-a", required=True)
    live.add_argument("--dsn-b", required=True)
    gov = sub.add_parser("governed", help="compute the governed target fingerprint of a live DSN")
    gov.add_argument("--dsn", required=True)
    pre = sub.add_parser("pre-adopt", help="read-only P3 pre-adoption precondition checks")
    pre.add_argument("--dsn", required=True)
    post = sub.add_parser("post-adopt", help="post-adoption conformance + governed convergence")
    post.add_argument("--dsn-fresh", required=True)
    post.add_argument("--dsn-adopted", required=True)
    sub.add_parser("receipt-bind", help="verify producing-commit-to-receipt-tip binding (commit 2 only)")
    args = parser.parse_args()
    try:
        if args.command == "static":
            static_verify()
        elif args.command == "live":
            static_verify()
            live_verify(args.dsn_a, args.dsn_b)
        elif args.command == "governed":
            print(governed_fingerprint_of(args.dsn))
        elif args.command == "pre-adopt":
            pre_adopt_verify(args.dsn)
        elif args.command == "post-adopt":
            post_adopt_verify(args.dsn_fresh, args.dsn_adopted)
        elif args.command == "receipt-bind":
            receipt_bind_verify()
    except (AssertionError, KeyError, RuntimeError, ValueError) as exc:
        print(f"G3 VERIFY FAIL: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
