#!/usr/bin/env python3
"""Build the repository-derived P0 schema used only by backend CI tests."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS = ROOT / "migrations"
P0 = MIGRATIONS / "ci" / "p0"

SKIP = {"005_agent_esaa.sql"}
REPLACE = {"016_normalize_permissions.sql": P0 / "016_permissions.sql"}

LEGACY_018_PERMISSIONS = """INSERT INTO permissions (name, description) VALUES
    ('agents.create',            'Create agent identities'),
    ('agents.read',              'Read agent identities'),
    ('agents.update',            'Update agent identities'),
    ('agents.disable',           'Disable agent identities'),
    ('agents.grants.create',     'Create agent tool grants'),
    ('agents.grants.read',       'Read agent tool grants'),
    ('agents.grants.revoke',     'Revoke agent tool grants'),
    ('agents.runs.create',       'Create agent runs'),
    ('agents.runs.read',         'Read agent runs'),
    ('agents.runs.cancel',       'Cancel agent runs'),
    ('agents.intentions.create', 'Create agent intentions'),
    ('agents.intentions.read',   'Read agent intentions'),
    ('agents.tools.execute',     'Execute tools via agent gateway')
ON CONFLICT (name) DO NOTHING;"""

P0_018_PERMISSIONS = """INSERT INTO permissions (name, description, resource, action, risk_level) VALUES
    ('agents.create',            'Create agent identities',         'agents',            'create',  'high'),
    ('agents.read',              'Read agent identities',           'agents',            'read',    'low'),
    ('agents.update',            'Update agent identities',         'agents',            'update',  'high'),
    ('agents.disable',           'Disable agent identities',        'agents',            'disable', 'high'),
    ('agents.grants.create',     'Create agent tool grants',        'agents.grants',     'create',  'high'),
    ('agents.grants.read',       'Read agent tool grants',          'agents.grants',     'read',    'low'),
    ('agents.grants.revoke',     'Revoke agent tool grants',        'agents.grants',     'revoke',  'high'),
    ('agents.runs.create',       'Create agent runs',               'agents.runs',       'create',  'medium'),
    ('agents.runs.read',         'Read agent runs',                 'agents.runs',       'read',    'low'),
    ('agents.runs.cancel',       'Cancel agent runs',               'agents.runs',       'cancel',  'high'),
    ('agents.intentions.create', 'Create agent intentions',         'agents.intentions', 'create',  'medium'),
    ('agents.intentions.read',   'Read agent intentions',           'agents.intentions', 'read',    'low'),
    ('agents.tools.execute',     'Execute tools via agent gateway', 'agents.tools',      'execute', 'critical')
ON CONFLICT (name) DO NOTHING;"""


def migration_files() -> list[Path]:
    files = sorted(MIGRATIONS.glob("[0-9][0-9][0-9]_*.sql"))
    if len(files) != 40:
        raise SystemExit(f"expected 40 repository migrations, found {len(files)}")
    return files


def normalized(path: Path) -> str:
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def patch_018(sql: str) -> str:
    if sql.count(LEGACY_018_PERMISSIONS) != 1:
        raise SystemExit("migration 018 permission block changed; update the P0 builder")
    return sql.replace(LEGACY_018_PERMISSIONS, P0_018_PERMISSIONS, 1)


def render() -> str:
    parts = [
        "-- ClarityIT repository-derived P0 backend test schema\n",
        "-- CI fixture only: not P1/P2/P3, G2/G3, install, or upgrade authority.\n",
        "-- Generated by scripts/build-ci-p0-schema.py; do not edit output.\n",
    ]

    for path in migration_files():
        parts.append(f"\n-- BEGIN REPOSITORY SOURCE {path.name}\n")
        if path.name in SKIP:
            parts.append(
                "-- Skipped in P0: migration 018 supplies the application-used "
                "agent schema.\n"
            )
        else:
            source = REPLACE.get(path.name, path)
            sql = normalized(source)
            if path.name == "018_phase7_agent_runtime.sql":
                sql = patch_018(sql)
            parts.append(sql)
        parts.append(f"-- END REPOSITORY SOURCE {path.name}\n")

    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    content = render()
    args.output.write_text(content, encoding="utf-8")
    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
    print(f"P0 test schema sha256={digest} path={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
